[2022-06-03 19:29:47,708] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: nyc_bus_breakdown_pipeline.processing_data manual__2022-06-03T19:29:42.324704+00:00 [queued]>
[2022-06-03 19:29:47,719] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: nyc_bus_breakdown_pipeline.processing_data manual__2022-06-03T19:29:42.324704+00:00 [queued]>
[2022-06-03 19:29:47,720] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-06-03 19:29:47,720] {taskinstance.py:1358} INFO - Starting attempt 1 of 2
[2022-06-03 19:29:47,721] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-06-03 19:29:47,736] {taskinstance.py:1378} INFO - Executing <Task(PythonOperator): processing_data> on 2022-06-03 19:29:42.324704+00:00
[2022-06-03 19:29:47,740] {standard_task_runner.py:52} INFO - Started process 723 to run task
[2022-06-03 19:29:47,745] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'nyc_bus_breakdown_pipeline', 'processing_data', 'manual__2022-06-03T19:29:42.324704+00:00', '--job-id', '335', '--raw', '--subdir', 'DAGS_FOLDER/nycbus_etl.py', '--cfg-path', '/tmp/tmp1m749el6', '--error-file', '/tmp/tmp3k1o6c_q']
[2022-06-03 19:29:47,746] {standard_task_runner.py:80} INFO - Job 335: Subtask processing_data
[2022-06-03 19:29:47,816] {task_command.py:370} INFO - Running <TaskInstance: nyc_bus_breakdown_pipeline.processing_data manual__2022-06-03T19:29:42.324704+00:00 [running]> on host d31a31117917
[2022-06-03 19:29:48,104] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=nyc_bus_breakdown_pipeline
AIRFLOW_CTX_TASK_ID=processing_data
AIRFLOW_CTX_EXECUTION_DATE=2022-06-03T19:29:42.324704+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-03T19:29:42.324704+00:00
[2022-06-03 19:29:49,074] {base.py:68} INFO - Using connection ID 's3_conn' for task execution.
[2022-06-03 19:29:49,076] {base_aws.py:210} INFO - Credentials retrieved from extra_config
[2022-06-03 19:29:50,947] {python.py:173} INFO - Done. Returned value was: None
[2022-06-03 19:29:50,968] {taskinstance.py:1401} INFO - Marking task as SUCCESS. dag_id=nyc_bus_breakdown_pipeline, task_id=processing_data, execution_date=20220603T192942, start_date=20220603T192947, end_date=20220603T192950
[2022-06-03 19:29:51,009] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-03 19:29:51,043] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
